---
title: "our TODO"
format: html
embed-resources: true
---

# Project Title Ideas

- The Simulation Project (overall possible title - there may be subprojects with subtitles)


# General Goals

## Theory

- [ ] Review the variance formulation in Freedman - the number of significant variables is not a Bin(50,0.25) (50 = number of variables and 0.20 = alpha level of each test of significance) because each test of a variable's significance is not an *independent* trial!  These tests are dependent. The expected number of significant tests is 50\*.25 = 12.5 but the variance is not 50\*.25\*(1-.25) = 9.375 due to the dependence of the tests. We can show this empirically with the simulations. It would be awesome to figure out the theoretical variance thus we need to know *how* the tests are correlated with each other. X = number of significant covariates under then null (i.e. all noise covars) then EX = n\*p and VarX = ?
- [x] Understand Flack and Chang paper

## Development Code

- [x] Develop a function for Freedman simulation
- [ ] Write code for Flack simulation
- [ ] Learn and implement R classes so our simulation functions produce similar output when called by summary or plot

## Documentation

- [ ] Document the current state of Freedman function

## Testing

- [ ] Write some tests for checking the Freedman function

# Current R packages with Sims

Lists of current R packages with relevant simulation capabilities.

- [survsim](https://cran.r-project.org/web/packages/survsim/index.html): simple and complex survival data including recurrent and multiple events AND competing risks.

# Potential Papers and the Things To Do for/Thoughts on each Paper

## General Simulation Study Design/Theory

### Morris, White, & Crowther

Morris TP, White IR, Crowther MJ. Using simulation studies to evaluate statistical methods. Stat Med. 2019 May 20;38(11):2074-2102. doi: 10.1002/sim.8086. Epub 2019 Jan 16. PMID: 30652356; PMCID: PMC6492164.

- Need to spec out their framework and see if that can be generalized to other simulation designs:  ADEMP = Aims, Data generating mechansims, Estimands, Methods, Performance measures
  
- What simulation output is typically reported? 

## Multiple Linear Regression 

Focusing mostly on variable selection techniques. Could slot in other theory to investigate, if anyone is interested.

### Freedman

Freedman, D. A. (1983), "A Note on Screening Regression Equations", *The American Statistician*, 37, 152-155.

- Some framing around (1) the expected number of significant variables in the first model to be 12.5 (= $n\times p = 50 \times 0.25$) but that this is *not* a Bin(50,25) because each test is not *independent* and (2) the data as generated do to exactly follow Freedman's theory as the X's are not orthogonal (as is assumed - check this - in the paper's derivations)
- What about the degree of spurious correlation between Y and X's?  Anyway to decorrelate these? Such as a PCA on the [y x1 .... x50] matrix?  Is that even reasonable?

### Flack & Chang

Flack, V. F., & Chang, P. C. (1987). Frequency of Selecting Noise Variables in Subset Regression Analysis: A Simulation Study. The American Statistician, 41(1), 84–86. https://doi.org/10.1080/00031305.1987.10475450

- Note that the autocorrelation pattern of the P candidate variables with the stated choice of subscripts would not give a true regression equation as stated. Their $\rho_{ij} = \rho^{j-i+1}$ for $j > i = 1, \cdots, p-1$, but it appears they should have $\rho_{ij} = \rho^{j-i}$ for $j > i = 1, \cdots, p$...  $\rho^{|j-i|}$ can be used for $j \neq i \in 1:p$ which gives an AR(1) correlation matrix which would give their true regression equation and Table 1 $\beta$ coefficients. With their stated $\rho_{ij}$ the true regression equation will be different... we can use simulations to show this!  (But also get the true regression equations analytically... details forthcoming!) 

- Can partially frame this around connections to intro Math/Stat theory (e.g. MVN results).

### Freedman & Pee

Freedman, L. S., & Pee, D. (1989). Return to a Note on Screening Regression Equations. The American Statistician, 43(4), 279–282. https://doi.org/10.1080/00031305.1989.10475675

### Derksen & Keselman

Derksen, S.A., & Keselman, H.J. (1992). Backward, forward and stepwise automated subset selection algorithms: Frequency of obtaining authentic and noise variables. British Journal of Mathematical and Statistical Psychology, 45, 265-282.

### Tibshirani

Robert Tibshirani, Regression Shrinkage and Selection Via the Lasso, Journal of the Royal Statistical Society: Series B (Methodological), Volume 58, Issue 1, January 1996, Pages 267–288, https://doi.org/10.1111/j.2517-6161.1996.tb02080.x

### Hastie, Tibshirani, & Tibshirani

Trevor Hastie, Robert Tibshirani, Ryan Tibshirani. "Best Subset, Forward Stepwise or Lasso? Analysis and Recommendations Based on Extensive Comparisons." Statistical Science, 35(4) 579-592 November 2020.
https://doi.org/10.1214/19-STS733

## GLM

Perhaps some count data simulations just to extend the previous work. 

## Linear Mixed Models 

Simulating dependence structures, which seems a decent prerequisite for multistate models.

Concepts to consider:  random intercept models, random slope models, more complex structures, hierarchical data generation, covariance specificiation, convergence issues

- Can compare power between different study designs which incorporate information repeated measures structure vs. not and look at the impact of sample size and within vs between individual variation. 

  For example suppose you have 60 individuals and two choices of experimental design: (1) randomly assign 20 each to the three sessions for vs. (2) measure all 60 at every session.  In both cases you have n = 60 independent sampling units (participants), but in the 2nd case if you include all 3 sessions with the appropriate dependency structure incorporated in a mixed model the effective sample size should be somewhere between 60 and 180. (What this effective sample size is depends on the within-subject correlation and the specific parameter of interest that is being assessed so it is not straightforward to define or even calculate.) 

  So, including all repeated measures across individuals and including a correct dependence structure should give us a larger (effective) sample size which typically increases the precision of our estimates and thus might provide greater power. 

  An alternative design would be to have 180 independent individuals and  randomly assign 60 to each session. Here there is no dependency structure and all 180 observations are independent. Whether this design has more or less power than the repeated-measures design depends on the within-subject correlation and variance structure, so power is not determined solely by the nominal sample size. 

###  Baayen, Davidson, & Bates

R.H. Baayen, D.J. Davidson, D.M. Bates, Mixed-effects modeling with crossed random effects for subjects and items, Journal of Memory and Language, Volume 59, Issue 4, 2008, Pages 390-412, ISSN 0749-596X,
https://doi.org/10.1016/j.jml.2007.12.005. (https://www.sciencedirect.com/science/article/pii/S0749596X07001398)

### Brown

Brown, V. A. (2021). An introduction to linear mixed-effects modeling in R. Advances in Methods and Practices in Psychological Science, 4(1), Article 2515245920960351. https://doi.org/10.1177/2515245920960351

I don't think this has any simulations but it does give an overview of lmes in R so might be helpful for background.

## Survival

There are lots of concepts here that seem important:  

  - Time-to-event 
  - Counting process formulation 
  - Different modeling approaches? (e.g. Andersen-Gill, Prentice-Williams-Peterson models)
  - Frailty terms
  - Proportional vs non-proportional hazards
  - AFT models
  - Competing risk
  - Recurrent events

This can get big fast!

### Volinsky, Madigan, Raferty, and Kronmal 

Chris T. Volinsky, David Madigan, Adrian E. Raftery, & Richard A. Kronmal. (1997) Bayesian model averaging in proportional hazard models: Assessing the risk of a stroke. Applied Statistics, 46, No. 4, 433-448. 

Note my long term quote that I used to have up is from this paper: "There are now many references exposing the problems with this general approach. Freedman (1983) and Flack and Chang (1987) demonstrated the tendency of step-wise methods to select pure noise variables as signi®cant, especially when there is multicollinearity among the explanatory variables or when the ratio of the number of variables to the number of records is high."

This might be a good read but there aren't any simulations in it (that I see on a cursory glance) and it is outside of what we are really interested in. Here mostly to indicate one source of motivation for examining Freedman and Flack and Chang. 

### Tibshirani

Tibshirani R. The lasso method for variable selection in the Cox model. Stat Med. 1997 Feb 28;16(4):385-95. doi: 10.1002/(sici)1097-0258(19970228)16:4<385::aid-sim380>3.0.co;2-3. PMID: 9044528.

### Bender, Augustin, & Blettner

Bender R, Augustin T, Blettner M. Generating survival times to simulate Cox proportional hazards models. Stat Med. 2005 Jun 15;24(11):1713-23. doi: 10.1002/sim.2059. PMID: 15724232. https://onlinelibrary.wiley.com/doi/abs/10.1002/sim.2673

### Burton, Altman, Royson, & Holder

Burton, A., Altman, D.G., Royston, P. and Holder, R.L. (2006), The design of simulation studies in medical statistics. Statist. Med., 25: 4279-4292. https://doi.org/10.1002/sim.2673

### Crowther & Lambert

Crowther MJ, Lambert PC. Simulating biologically plausible complex survival data. Stat Med. 2013 Oct 15;32(23):4118-34. doi: 10.1002/sim.5823. Epub 2013 Apr 23. PMID: 23613458.

## Multistate Models

## Distributions

### Headrick

Todd C. Headrick, Fast fifth-order polynomial transforms for generating univariate and multivariate nonnormal distributions, Computational Statistics & Data Analysis, Volume 40, Issue 4, 2002, Pages 685-711, ISSN 0167-9473, https://doi.org/10.1016/S0167-9473(02)00072-5.(https://www.sciencedirect.com/science/article/pii/S0167947302000725)

### Pant, Chakraborty, & El Moudden

Pant MD, Chakraborty A, Moudden IE. Modeling Non-Normal Distributions with Mixed Third-Order Polynomials of Standard Normal and Logistic Variables. Mathematics. 2025; 13(6):1019. https://doi.org/10.3390/math13061019 

### Qu, Liu, & Zhang

Qu, W., Liu, H. & Zhang, Z. A method of generating multivariate non-normal random numbers with desired multivariate skewness and kurtosis. Behav Res 52, 939–946 (2020). https://doi.org/10.3758/s13428-019-01291-5

### Fairchild, Yin, Baraldi, Astivia, & Shi

Fairchild, A.J., Yin, Y., Baraldi, A.N. et al. Many nonnormalities, one simulation: Do different data generation algorithms affect study results?. Behav Res 56, 6464–6484 (2024). https://doi.org/10.3758/s13428-024-02364-w

## Testing Normality

### Shapiro & Wilk

Shapiro SS and Wilk MB. An analysis of variance test for normality (complete samples).  Biometrika. 1965;52(3/4):591-611. 

### Razali & Wah

Razali NM and Wah YB. Power comparisons of Shapiro-Wilk, Kolmogorov-Smirnov, Lilliefors and Anderson-Darling tests. Journal of Statistical Modeling and Analytics. 2011;2(1):21-33.

## Other methods?

# Brainstorming/Spitballing

A place to add ideas for future pursuits, things we should be focusing on, etc. 

- What are possible ways to formulate or spin this for publication(s)?  As educational tools.  As replication of studies.
- For implementing R classes, what is the "default" output we want returned when a simulation function is run without saving in a variable? For example, the `lm()` function returns the "Call" and the coefficient estimates from the fitted model.  We could return something around time it took to run the given simulation along with some "Call" type of information. 
- Should we have a simulation approach from the point of view of the "study design" vs. "method applied"?  E.g. generate different study designs:  iid, experimental, cohort, cross-over, longitudinal,... (would have to look up some standard design styles)
- Long term:  What about involving others?!  In particular, students could contribute around a specific paper as a capstone project. This might be a way to really grow what is covered in the package - new simulations/methods/study designs can be added by different contributors.
- Other projects? Not necessarily sims but maybe can be rehashed to include them (maybe)

  - LBP Markov Analysis Paper: revisit goals of this. This was the basis of your 2024 (?!) SDSS presentation and paper.  Has this been updated?
  - I have a risk calculator paper draft for CTS (carpal tunnel syndrome). Maybe revisit this?
  - 


